app:
  db-vendor: opengauss

spring:
  datasource:
    driver-class-name: org.opengauss.Driver
    url: jdbc:opengauss://116.205.99.104:26000/car_sales?sslmode=disable
    username: qhd
    password: Qhd20041104
