app:
  db-vendor: opengauss

spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.opengauss.Driver}
    url: ${DB_URL:jdbc:opengauss://127.0.0.1:26000/car_sales?sslmode=disable&currentSchema=public}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD}
